name: ci
on:
  push:
    tags:
      - v*
    branches: 
      - master
  pull_request:
    branches: 
      - master
jobs:

  go-cleanarch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16.5' 
      - name: Install go-cleanarch
        run: go get -v -u github.com/roblaszczak/go-cleanarch
      - name: Clean Architecture checker for Golang
        run: go-cleanarch

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get dependencies
        run: |
          go version
          go get -v -t -d ./...
      - name: Build
        run: go build -v ./...

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: go test -v ./... 

  codecov:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate coverage report
        run: |
          go version
          go test `go list ./... | grep -v examples` -coverprofile=coverage.txt -covermode=atomic
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          file: ./coverage.txt
          flags: unittests
          name: codecov-umbrella
          verbose: true
