name: ci
on:
  push:
    tags:
      - v*
    branches: 
      - master
  pull_request:
    branches: 
      - master
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
  
  lint:
    needs: setup
    runs-on: ubuntu-latest
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: latest

  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Build
      run: go build -v ./...

  test:
    needs: setup
    name: codecov
    runs-on: ubuntu-latest
    - name: Generate coverage report
      run: |
        go test `go list ./... | grep -v examples` -coverprofile=coverage.txt -covermode=atomic

  codecov:
    needs: test
    name: codecov
    runs-on: ubuntu-latest
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        file: ./coverage.txt
        flags: unittests
        name: codecov-umbrella
        verbose: true
