name: katarina
on:
  push:
    tags:
      - v*
    branches: 
      - master
      - katarina-test
  pull_request:
    branches: 
      - master
      - katarina-test
jobs:

  env-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 
      - name: Test env
        run: echo $KATARINA

